name: "Setup Rust"
description: "Setup Rust"

outputs:
  rustc-hash:
    description: "Hash of the rustc version"
    value: ${{ steps.rust-version.outputs.rustc_hash }}

runs:
  using: "composite"
  steps:
    # Cache Rust toolchain and Cargo artifacts
    - uses: actions/cache@v3
      name: Cache Rust Toolchain and Cargo Artifacts
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
          ~/.rustup
        key: rust-toolchain-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Install system packages
      run: sudo apt-get update && sudo apt-get install -y build-essential libudev-dev
      shell: bash

    - name: Install Rust nightly
      run: |
        rustup default nightly
        rustup component add rustfmt clippy
      shell: bash

    - name: Install Cargo Expand
      run: cargo install --locked cargo-expand
      shell: bash
