name: "Setup Trident"
description: "Setup Trident"

runs:
  using: "composite"
  steps:
    - name: Clone Trident at specified commit and Install
      run: |
        if ! command -v trident &> /dev/null; then
          git clone --depth 1 https://github.com/Ackee-Blockchain/trident.git
          cd trident
          git checkout ${{ env.TRIDENT_COMMIT_HASH }}
          cargo install --path crates/cli
        else
          echo "Trident is already installed, skipping installation."
        fi
      shell: bash
